 *
 * This file is automatically generated by WebPageToCCode
 * Do not modify ths file, changes will not persist!
 */

#include "website.h"
#include <sys/param.h>

struct web_content {
    size_t length;
    const char* data;
    bool compression;
    const char* content_type;
};

esp_err_t website_content_handler(httpd_req_t *req)
{
    int ret = 0;
    struct web_content* ctx = req->user_ctx;
    int remaining = ctx->length;

    httpd_resp_set_status(req, HTTPD_200);
    httpd_resp_set_type(req, ctx->content_type);
    if (ctx->compression) {
        httpd_resp_set_hdr(req, "Content-Encoding", "gzip");
    }
    while (remaining > 0) {
        /* Read the data for the request */
        ret = MIN(remaining, CHUNKSIZE);

        /* Send back the same data */
        httpd_resp_send_chunk(req, ctx->data + (ctx->length - remaining), ret);
        remaining -= ret;
    }
    httpd_resp_send_chunk(req, NULL, 0);

    return ESP_OK;
}
